# SPDX-FileCopyrightText: 2024 Samuel W. Flint <me@samuelwflint.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

image: nixos/unstable
packages:
  - nixos.emacs
  - nixos.hut
  - nixos.python3
  - nixos.reuse
sources:
  - https://github.com/riscy/melpazoid
artifacts:
  - package-archive.tar.gz
tasks:
  - setup-emacs: |
      emacs --batch -l emacs-universal-sidecar/build/init.el -f build/package-install-prereqs
  - license-lint: |
      cd emacs-universal-sidecar
      reuse lint || echo
  - lint-all: |
      emacs --batch -l emacs-universal-sidecar/build/init.el -f package-lint-batch-and-exit emacs-universal-sidecar/*.el || echo
  - run-melpazoid: |
      export LOCAL_REPO='~/emacs-universal-sidecar/'
      set +x
      for recipe in ~/emacs-universal-sidecar/build/recipes/* ; do
          export RECIPE=$(cat ${recipe})
          set -x
          emacs --batch -l ~/emacs-universal-sidecar/build/init.el -l melpazoid/melpazoid/melpazoid.el || echo
          set +x
      done
  - byte-compile: |
      emacs --batch -l emacs-universal-sidecar/build/init.el -f batch-byte-compile emacs-universal-sidecar/*.el || echo
  - build-packages: |
      mkdir -p ~/package-archive/
      emacs --batch -l ~/emacs-universal-sidecar/build/init.el -f build/build-packages
  - build-archive: |
      cd ~/
      tar czvf ~/package-archive.tar.gz package-archive/
